[tasks.format]
command = "cargo"
args = ["fmt", "--all"]

[tasks.check]
command = "cargo"
args = ["check", "--workspace", "--examples", "--tests"]

[tasks.clippy]
command = "cargo"
args = [
    "clippy",
    "--workspace",
    "--examples",
    "--tests",
    "--",
    "-D",
    "warnings",
]

[tasks.tidy]
category = "Formatting"
dependencies = ["format", "check", "clippy"]
description = "Format and Check workspace"

[tasks.install-miri]
toolchain = "nightly"
install_crate = { rustup_component_name = "miri", binary = "cargo +nightly miri", test_arg = "--help" }
private = true

[tasks.miri-native]
command = "cargo"
toolchain = "nightly"
dependencies = ["install-miri"]
args = [
    "miri",
    "test",
    "--package",
    "dioxus-native-core",
    "--test",
    "miri_native",
]

[tasks.miri-stress]
command = "cargo"
toolchain = "nightly"
dependencies = ["install-miri"]
args = ["miri", "test", "--package", "dioxus-core", "--test", "miri_stress"]

[tasks.miri]
dependencies = ["miri-native", "miri-stress"]

[tasks.tests]
category = "Testing"
dependencies = ["tests-setup"]
description = "Run all tests"
env = { CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = ["**/examples/*"] }
run_task = { name = ["test-flow", "test-with-browser"], fork = true }

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test-flow]
dependencies = ["test", "docs"]
private = true

[tasks.test]
dependencies = ["build"]
command = "cargo"
args = [
    "test",
    "--lib",
    "--bins",
    "--tests",
    "--examples",
    "--workspace",
    # These tests run on Ubuntu without a screen. Desktop tests that require a screen fail, so we skip them
    "--exclude",
    "dioxus-desktop",
    "--exclude",
    "dioxus-mobile",
]
private = true

[tasks.docs]
dependencies = ["build"]
command = "cargo"
args = ["test", "--doc", "--workspace"]
private = true
